/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 13 23:41:36 GMT 2020
 */

package es.uca.muiisc.psi;

import org.junit.Test;
import static org.junit.Assert.*;
import es.uca.muiisc.psi.Room;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Room_ESTest extends Room_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Room room0 = new Room(0);
      int int0 = room0.getNumber();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Room room0 = new Room(1506);
      int int0 = room0.getNumber();
      assertEquals(1506, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Room room0 = new Room((-3));
      room0.getReservations();
      assertEquals((-3), room0.getNumber());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Room room0 = new Room((-3));
      int int0 = room0.getNumber();
      assertEquals((-3), int0);
  }
}
