/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 16 23:57:37 GMT 2019
 */

package es.uca.muiisc.psi;

import org.junit.Test;
import static org.junit.Assert.*;
import es.uca.muiisc.psi.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
  }
}
