/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 16 23:57:28 GMT 2019
 */

package es.uca.muiisc.psi;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import es.uca.muiisc.psi.Factorial;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Factorial_ESTest extends Factorial_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Factorial factorial0 = new Factorial();
      int int0 = (-1);
      int int1 = factorial0.factorial(int0);
      factorial0.factorial(int0);
      int int2 = 0;
      factorial0.factorial(int2);
      int int3 = 2389;
      factorial0.factorial(int3);
      int int4 = 1208;
      factorial0.factorial(int4);
      int int5 = factorial0.factorial(int2);
      int int6 = 925;
      factorial0.factorial(int6);
      int int7 = 116;
      factorial0.factorial(int7);
      factorial0.factorial(int4);
      factorial0.factorial(int4);
      int int8 = (-1516);
      factorial0.factorial(int8);
      int int9 = 2268;
      factorial0.factorial(int9);
      factorial0.factorial(int1);
      factorial0.factorial(int4);
      int int10 = 0;
      factorial0.factorial(int10);
      factorial0.factorial(int4);
      int int11 = 0;
      factorial0.factorial(int11);
      factorial0.factorial(int1);
      int int12 = 0;
      factorial0.factorial(int12);
      factorial0.factorial(int11);
      factorial0.factorial(int2);
      factorial0.factorial(int5);
      int int13 = 0;
      factorial0.factorial(int13);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Factorial factorial0 = new Factorial();
      factorial0.factorial(1);
      factorial0.factorial(1);
      factorial0.factorial(1);
      factorial0.factorial(1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Factorial factorial0 = new Factorial();
      int int0 = factorial0.factorial(1);
      int int1 = 0;
      int int2 = factorial0.factorial(int1);
      factorial0.factorial(int0);
      int int3 = 1;
      factorial0.factorial(int3);
      factorial0.factorial(int3);
      factorial0.factorial(int2);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Factorial factorial0 = new Factorial();
      int int0 = 391;
      int int1 = factorial0.factorial(391);
      factorial0.factorial(int1);
      int int2 = factorial0.factorial(int1);
      int int3 = factorial0.factorial(int1);
      int int4 = factorial0.factorial(int3);
      factorial0.factorial(int2);
      int int5 = 882;
      int int6 = factorial0.factorial(int5);
      factorial0.factorial(int6);
      int int7 = factorial0.factorial(int3);
      int int8 = 798;
      factorial0.factorial(int8);
      int int9 = factorial0.factorial(int4);
      factorial0.factorial(int7);
      factorial0.factorial(int9);
      int int10 = (-1);
      factorial0.factorial(int10);
      factorial0.factorial(int5);
      factorial0.factorial(int4);
      int int11 = (-745);
      factorial0.factorial(int11);
      factorial0.factorial(int1);
      factorial0.factorial(int9);
      factorial0.factorial(int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Factorial factorial0 = new Factorial();
      factorial0.factorial(139);
      factorial0.factorial(139);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Factorial factorial0 = new Factorial();
      factorial0.factorial(229);
      int int0 = 0;
      int int1 = factorial0.factorial(int0);
      int int2 = 0;
      factorial0.factorial(int2);
      int int3 = factorial0.factorial(int1);
      int int4 = 0;
      factorial0.factorial(int4);
      int int5 = 2159;
      factorial0.factorial(int5);
      int int6 = 2685;
      factorial0.factorial(int6);
      int int7 = (-1501);
      factorial0.factorial(int7);
      int int8 = 1;
      factorial0.factorial(int8);
      factorial0.factorial(int4);
      int int9 = 0;
      factorial0.factorial(int9);
      int int10 = factorial0.factorial(int7);
      int int11 = factorial0.factorial(int3);
      int int12 = (-3244);
      factorial0.factorial(int12);
      int int13 = 0;
      factorial0.factorial(int13);
      factorial0.factorial(int11);
      int int14 = 0;
      factorial0.factorial(int14);
      factorial0.factorial(int10);
      int int15 = 73;
      factorial0.factorial(int15);
      factorial0.factorial(int1);
      int int16 = (-1);
      factorial0.factorial(int16);
      int int17 = 0;
      factorial0.factorial(int17);
      int int18 = 0;
      factorial0.factorial(int18);
  }
}
